<?php

/**
 * @file
 * Module file for the ATC Change Request module. Drupal needs this file.
 */
// Location of Form Elements
// http://api.drupal.org/api/drupal/developer--topics--forms_api_reference.html/7

/**
 * Implements hook_node_access().
 */
function atc_changerequest_node_access($node, $op, $account) {
  $type = is_string($node) ? $node : $node->type;

  if (in_array($type, node_permissions_get_configured_types())) {
    if ($op == 'create' && user_access('create ' . $type . ' content', $account)) {
      return NODE_ACCESS_ALLOW;
    }

    if ($op == 'update') {
      if (user_access('edit any ' . $type . ' content', $account) || (user_access('edit own ' . $type . ' content', $account) && ($account->uid == $node->uid))) {
        return NODE_ACCESS_ALLOW;
      }
    }

    if ($op == 'delete') {
      if (user_access('delete any ' . $type . ' content', $account) || (user_access('delete own ' . $type . ' content', $account) && ($account->uid == $node->uid))) {
        return NODE_ACCESS_ALLOW;
      }
    }
  }

  return NODE_ACCESS_IGNORE;
}

/**
 * Implementation of hook_menu()
 */
 
function atc_changerequest_menu() {
  $items = array();
  // dsm('ATC Test Module');
  
  $items['admin/config/atc_changerequest'] = array(
    'path' => 'admin/config/atc_changerequest',
    'title' => t('ATC Change Request'),
    'description' => t('Add form elements to Change Request Form as needed'),
    'page callback' => 'atc_admin_settings',
 //   'callback' => 'drupal_get_form',
 //   'callback arguments' => array('annotate_admin_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration')
    );
  return $items;
  }

function atc_admin_settings() {
//	return "Hello World";

// Drupal from processing...
// drupal_get_form('my_form')
// my_form() - called function
// my_form_validate()
// drupal_render() - if validate false
// my_form_submit() - if validate true 
// drupal_redirect_form()

	// Drupal's form api
	
//	$form['foo'] = array(
//	  '#type' => 'textarea',
//	  '#title' => t('Enter text here'),	
//	  '#default_value' => 'Here we go...',  
//	);
	
//	$form['submit'] = array(
//	  '#type' => 'submit',
//	  '#value' => t('Pity the foo'),
//	);
	
//	$form['2'] = array(
	  
//	);
	
//	$form['3'] = array(
	
//	);
//	return $form;
	return drupal_get_form('atc_settings_form');
}

function atc_settings_form() {
	$form = array();
	
	$form['atctest'] = array(
		'#type' => 'textfield',
	   '#title' => t('Allow ATC Change Request Extention Form Elements'),
	   '#description' => t('Added Fields'),
	 //  '#options' => node_get_types('names'),
	//   '#default_value' => variable_get('atc_changerequest_nodetypes', array('page')),
	   '#required' => TRUE,
   );
   
   $form['atctest1'] = array(
		'#type' => 'textfield',
	   '#title' => t('Allow ATC Change Request Extention Form Elements'),
	   '#description' => t('Added Fields'),
	 //  '#options' => node_get_types('names'),
	//   '#default_value' => variable_get('atc_changerequest_nodetypes', array('page')),
	   '#required' => TRUE,
   );
   
	//$form['test1'] = array(
	//	'#type' => 'textfield',
	//   '#title' => t('Allow ATC Change Request Extention Form Elements'),
	 //  '#options' => node_get_types('names'),
	 //  '#default_value' => variable_get('atc_changerequest_nodetypes', array('page')),
	 //  '#description' => t('Added Fields'),
	 //  '#required' => TRUE,
   //);
   
   $form['atc_changerequest_nodetypes'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Allow ATC Change Request Extention Form Elements'),
 //   '#options' => node_get_types('names'),
    '#options' => array(t('Optional'), t('Required')),
 //   '#default_value' => variable_get('atc_changerequest_nodetypes', array('page')),
    '#description' => t('Added Fields'),
    );
   
	$form['modes'] = array(
		'#type' => 'fieldset',
		'#title' => t('Modes'),
	);
	
	$form['modes']['stalker'] = array(
		'#type' => 'checkbox',
		'#title' => t('Secrets'),
		'#description' => t('Description'),
		'#default_value' => t('testing'),
	);
	
	$form['modes']['stalker2'] = array(
		'#type' => 'checkbox',
		'#title' => t('Secrets2'),
		'#description' => t('Description2'),
		'#default_value' => t('testing2'),
	);
	
	$form['modes']['stalker3'] = array(
		'#type' => 'button',
		'#title' => t('Secrets2'),
		'#description' => t('Description2'),
		'#default_value' => t('Button Value'),
	);
   
	$form['submit'] = array(
	  '#type' => 'submit',
	  '#value' => t('Pity the foo'),
	);
	
	   $form['modes']['a'] = array(
    '#type' => 'radios',
    '#title' => t('Allow ATC Change Request Extention Form Elements'),
 //   '#options' => node_get_types('names'),
    '#options' => array(t('Optional'), t('Required')),
 //   '#default_value' => variable_get('atc_changerequest_nodetypes', array('page')),
    '#description' => t('Added Fields'),
    );
   return $form;
}
	
function atc_settings_form_validate(&$form, &$form_state) {
//	dsm($form_state);	
	if(!is_numeric($form_state['values']['atctest'])) {
		form_set_error('atctest', t('Enter a Numeric Value'));
	}
	elseif($form_state['values']['atctest'] < 1) {
		form_set_error('atctest', t('Numeric Value must be greater then 0'));
	}
}
	
// function is not working???
function atc_settings_form_submit(&$form, &$form_state) {
	variable_set('atctest', $form_state['values']['atctest']);
//	variable_set('atctest1', $form_state['values']['atctest1']);
   variable_set('atctest1', '123');
	// variable_set('test', - Variable in Data
	// $form_state['values']['test']);
}

/**
 * Define the settings form.
 */
 
function atc_admin_asdfsettings() {
  $form['atc_changerequest_nodetypes'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Allow ATC Change Request Extention Form Elements'),
    '#options' => node_get_types('names'),
    '#default_value' => variable_get('atc_changerequest_nodetypes', array('page')),
    '#description' => t('Added Fields'),
    );
    $form['array_filter'] = array('#type' => 'hidden');
    return system_form($form);
  }


